# --- Basic Site Settings ---
title: "Himgauri Pradeep Khaladkar"
author: "Himgauri Khaladkar"
email: "himgaurikhaladkar@gmail.com"
description: "Product Manager | Data Enthusiast | Engineering Management"
baseurl: "" # Leave blank unless you're using a subpath
url: "https://himgauripradeep.github.io" # Your GitHub Pages URL
favicon: "assets/img/favicon.ico"

# --- Navigation Bar ---
navbar-links:
  Home: "index"
  About: "about"
  Portfolio: "portfolio"
  Blog: "blog"
  GitHub: "https://github.com/himgauripradeep"
  Resume: "resume.pdf"
  Contact: "contact"

# --- Social Media Links ---
social-network-links:
  email: "himgaurikhaladkar@gmail.com"
  linkedin: "himgauri-khaladkar"
  github: "himgauripradeep"

# --- Appearance Settings ---
theme_skin: "dark" # Options: default, dark, minimal
show_downloads: false
show_excerpts: true
paginate: 5
paginate_path: "/blog/page:num/"


# --- Jekyll Plugins ---
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
